### PR TITLE
Build out Optimal Input Choice graph

### PR DESCRIPTION
**Pull request by nikolas**
I've changed the default gA1-A3 values to null in GraphMapping. These defaults depend on graph type, and can be set in the graph creation phase in GraphEditor.

Screenshot_2024-07-08_15-07-53

### CODE REVIEW

**Comment by Evan-CTL** [comment]
I'm encountering similar problems, but we can't hard assign values to these without causing problems. We need to check for a `create graph` state in some way and set initial values that won't be overwritten by hard-code

**Comment by nikolas** [comment]
Yeah - i just realized the GraphEditor is used in places that aren't the graph creation process. We can put this logic in `Editor` instead to resolve this, I'll update this pull request.

**Comment by Evan-CTL** [comment]
The defaults your setting aren't carried over on save either. They are going back to `{gA1: 2.5 , gA2: 2, gA3: 0.5}`
Screenshot 2024-07-09 at 11 07 32 AM

**Comment by Evan-CTL** [comment]
Looks good

**Pull request merged**
