### PR TITLE
Add 2nd set of range and stored values for a second function

### PR DESCRIPTION
**Pull request by Evan-CTL**
This syntax works better for the current build.

### CODE REVIEW

**Comment by nikolas** [comment]
What is the reason for renaming these fields? I think the old names are fine.

**Comment by Evan-CTL** [comment]
In the case of `<DefineRange>` it is expecting `Min` and `Max` to be at the end of the property name
Screenshot 2024-07-29 at 12 51 07 PM

**Comment by Evan-CTL** [comment]
I think it's a more usable hierarchy to have `[property_name] + [property_number] + [property_subtype]` That way you can iterate more easily through a list.

**Comment by nikolas** [comment]
The code in the DefineRange component shouldn't be relying on the structure of the property's name to function properly. We should refactor that code rather than change these property names.

**Comment by Evan-CTL** [comment]
It would be a more complicated refactor than just renaming them. Why is it bad practice?

**Comment by nikolas** [comment]
This is bad practice because the property names we've decided on are arbitrary and don't have a defined structure we rely on in the code. If we want to attach meaning to them to the level, that's tying the code to our data model which will very possibly change in the future.

What this code is doing is not that complicated - just rendering some markup. I would refactor that to not iterate over those properties. But if you want to keep the array iteration, you can get it working by adding the min and max values directly to the array you're iterating on. 

```
[
    ['gXAxis', 'X Axis', 'gXAxisMin', 'gXAxisMax'], // or whatever the property names are
    // etc.
]
```

**Comment by Evan-CTL** [comment]
Understood. Will do

**Pull request closed without merging**
