### PR TITLE
Fix isocost line to touch isoquant

### PR DESCRIPTION
**Pull request by nikolas**
When "Enable Cobb-Douglas" toggle is enabled in graph type 21.

I am aware of a remaining issue where the optimal bundle point is slightly off, but I'm getting closer, and all the other function types should be more routine once this one is done.

optimal_choice_cost_minimizing

### CODE REVIEW

**Comment by Evan-CTL** [comment]
I'm still getting this onLoad, after I check `Enable Cobb-Douglas Production Function`
Screenshot 2024-07-22 at 11 59 20 AM
It gets worse if I play with the sliders
Screenshot 2024-07-22 at 12 02 03 PM

**Comment by nikolas** [comment]
This change just fixes the isocost line, not the optimal bundle position, so ignore that. I am having trouble reproducing the behavior you're seeing though - are you sure you are loading the up to date built version of the javascript?

Screenshot_2024-07-22_12-07-06

I'm also going to rebase this branch as there has been some unrelated changes on master.

**Comment by Evan-CTL** [comment]
I'm not sure what's wrong, but I keep getting the same thing. I've tried pulling from `master` and`isocost-fix`. I've tried rebasing `isocost-fix` from `origin`. I've tried running `make clean` and rebuilding from scratch. There is no `make build` or `npm run build`. I'm not sure what the difference is.

**Comment by nikolas** [comment]
`npm run build` and `npm run dev` are defined in the package.json - https://github.com/ccnmtl/econplayground/blob/master/package.json#L29

`npm run build` is used on production - I generally use `npm run dev` in development.

**Comment by nikolas** [comment]
Also, it could be a git problem you're having - delete your local `isocost-fix` branch as it may be out of date:
```
git branch -D isocost-fix
git fetch origin
git checkout isocost-fix
```

That will download the up-to-date branch from github.

**Comment by Evan-CTL** [comment]
Still no luck. Should I merge it and see if it works in production?

**Comment by nikolas** [comment]
Interesting - I suppose it is possible we are seeing a strange bug in the code that's behaving differently in our two environments. Let me think about what to do next.

**Comment by nikolas** [comment]
The behavior you're seeing is what you would be seeing on the master branch. This view loads the `media/js/build/editor.js` file - you can do a `ls -l media/js/build/editor.js` to ensure the timestamp is up to date. Both `npm run build` and `npm run dev` will update this file.

I think let's just merge this, and if you see this issue on production, we'll handle it separately as a bug.

**Pull request merged**
